version: '3.1'
services:
  nginx:
    image: nginx:latest
    container_name: qa_nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx-qa:/etc/nginx/conf.d
      - .:/usr/src/app
    depends_on:
      - web
    networks:
      - qabublenet   
  redis:
    image: redis
    container_name: qa_redis
    networks:
      - qabublenet   
  web:
    build: .
    command: "bin/bundle exec rails s -e qa -p 3000 -b 0.0.0.0"
    volumes:
      - .:/app
    expose:
      - "3000"
    container_name: qa_web
    networks:
      - qabublenet  
    depends_on:
      - redis  
    environment:
      - "REDIS_URL=redis"
networks:
 qabublenet:
    driver: bridge  
